export const MUTATE_SET_PARTICIPANTS = 'MUTATE_SET_PARTICIPANTS';
export const MUTATE_ADD_PARTICIPANT = 'MUTATE_ADD_PARTICIPANT';
export const MUTATE_UPDATE_PARTICIPANT = 'MUTATE_UPDATE_PARTICIPANT';

export const MUTATE_SET_COUNTRIES = 'MUTATE_SET_COUNTRIES';